const SELL_ICE_CREAM = 'SELL_ICE_CREAM'
const PUT_SCOOP = 'PUT_SCOOP'
const CANCEL_SELLING = 'CANCEL_SELLING'
const CLEAN_CORNET = 'CLEAN_CORNET'


export {SELL_ICE_CREAM, PUT_SCOOP, CANCEL_SELLING, CLEAN_CORNET}